### ISSUE TITLE
 Error connecting to https://us.gcr.io using address us.gcr.io:443

### ISSUE THREAD

**Issue by a1983877922** [rahulg603/mtSwirl#6]
hi,rahulg，Why Pipeline need to connect https://us.gcr.io；
[2024-02-24 00:54:22,33] [info] Request threw an exception on attempt #1. Retrying after 989 milliseconds
org.http4s.client.ConnectionFailure: Error connecting to https://us.gcr.io using address us.gcr.io:443 (unresolved: false)
        at org.http4s.client.blaze.Http1Support.$anonfun$buildPipeline$1(Http1Support.scala:90)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:477)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at async @ org.http4s.internal.package$.$anonfun$fromFuture$1(package.scala:144)
        at flatMap @ org.http4s.internal.package$.fromFuture(package.scala:139)
        at flatMap @ org.http4s.client.PoolManager.$anonfun$createConnection$2(PoolManager.scala:119)
        at shift @ org.http4s.client.PoolManager.$anonfun$createConnection$2(PoolManager.scala:119)
        at uncancelable @ org.http4s.client.ConnectionManager$.pool(ConnectionManager.scala:83)
        at unsafeRunSync @ cromwell.docker.DockerInfoActor.preStart(DockerInfoActor.scala:173)

**Comment by rahulg603** [comment]
Hi! Which platform are you running the pipeline on? What are you using for your inputs.json?

**Comment by a1983877922** [comment]
> Hi! Which platform are you running the pipeline on? What are you using for your inputs.json?
I've changed the wdl code to change the docker that needs to be networked（[https://us.gcr.io]）to local
